### ISSUE TITLE
Not working well with TombManyGraves and also Gravestone sorta

### ISSUE THREAD

**Issue by Whazaaaaa** [runescapejon/KeepInventory-Sponge#2]
So this plugin doesnt quite work very well together with modpacks that have a gravestone mod.

For example. The [TombManyGraves](https://minecraft.curseforge.com/projects/tomb-many-graves-2) mod still places its grave and keeps all the items inside
And the [Gravestone](https://minecraft.curseforge.com/projects/gravestone-mod) mod places down a grave but in this case you do keep your items. But it still leaves an empty grave.

Any way for you to fix this? I'd rather not remove the mods from the modpack on the server.

**Comment by runescapejon** [comment]
Hello,
I believe this is a more of a sponge issue, 
personally dont think sponge api keepinventory will work at all with because the way the mod works

**Comment by Whazaaaaa** [comment]
Thats what I was afraid of. Thanks anyway :)
