### ISSUE TITLE
Plugin Config

### ISSUE THREAD

**Issue by Spontini** [runescapejon/KeepInventory-Sponge#3]
Current config is like;
Languages {
    KeepInventoryMessage="&6&lYour whole inventory was saved from your recent Death."
}
This right now for example if i change message into [KeepInventory] Your whole inventory was saved from your recent Death.
the player will get the message like this
Explosive  [KeepInventory] Your whole inventory was saved from your recent Death.

Can you please fix this? Thank you

**Comment by runescapejon** [comment]
Oops
EDIT: fixin

**Comment by runescapejon** [comment]
https://ore.spongepowered.org/runescapejon/KeepInventory/versions/1.3

**Comment by Spontini** [comment]
Thanks man

**Comment by Spontini** [comment]
Update: I just installed plugin and it doesn't create a config file D:

**Comment by runescapejon** [comment]
for real?

**Comment by Spontini** [comment]
Yep, for real 💃

**Comment by runescapejon** [comment]
Haha my mistake on this one fixing now

**Comment by Spontini** [comment]
It's fine, thank you again :P

**Comment by runescapejon** [comment]
https://ore.spongepowered.org/runescapejon/KeepInventory/versions/1.3.1
