### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Spontini** [runescapejon/KeepInventory-Sponge#4]
If you use this plugin + soulbound enchantment it will dupe the item with soulbound enchantment everytime you die.

**Comment by runescapejon** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2892
Sponge bug

**Comment by Spontini** [comment]
@runescapejon However the dupe bug does not happen if you run `/gamerule keepInventory true`

**Comment by runescapejon** [comment]
That because that part is not utilize by sponge that cause the bug
